# ===== build stage =====
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /src

# Copiamos primero solución y después código para aprovechar la cache
COPY ./Scalable.sln ./
COPY ./src ./src

RUN dotnet restore ./Scalable.sln
RUN dotnet publish ./src/Api/Api.csproj -c Release -o /app/publish /p:UseAppHost=false

# ===== runtime stage =====
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS runtime
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Api.dll"]