name: cd

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo ">>> Deploying scalable-api ${{ github.sha }}"

            # Crear o actualizar el directorio de la app
            sudo mkdir -p /opt/scalable && sudo chown $USER:$USER /opt/scalable
            cd /opt/scalable

            # Crear archivo docker-compose con la imagen del commit actual
            cat > docker-compose.prod.yml <<'YAML'
            version: "3.9"
            services:
              api:
                image: ghcr.io/isaivazqez/scalable-api:${{ github.sha }}
                pull_policy: always
                container_name: scalable_api
                restart: unless-stopped
                environment:
                  ASPNETCORE_ENVIRONMENT: Production
                ports:
                  - "80:8080"
            YAML

            # Login a GHCR
            echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u isaivazqez --password-stdin

            # Pull y arranque
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d

            echo ">>> Healthcheck"
            curl -fsS -X POST http://localhost/graphql \
              -H "Content-Type: application/json" \
              -d '{"query":"{ ping }"}' || (echo "Healthcheck failed" && exit 1)