name: cd

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/isaivazqez/scalable-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ops/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:main-latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/scalable
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            curl -fsS -X POST http://localhost/graphql -H "Content-Type: application/json" -d '{"query":"{ ping }"}' || (echo "Healthcheck failed" && exit 1)