name: ci

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/isaivazqez/scalable-api   # 👈 todo minúsculas

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}          # o ponlo literal, pero no hace falta
          password: ${{ secrets.GITHUB_TOKEN }}  # usa el token automático del workflow

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ops/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:main-latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}